### ISSUE TITLE
facing entry point isssue in native script

### ISSUE THREAD

**Issue by kapil9-10** [NativeScript/nativescript-datetimepicker#73]
i want to use datepicker and Redautocompletetextbox but for both it's showing entry point error 

package.json

"dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@nativescript/angular": "~9.0.0",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-intl": "^4.0.1",
    "nativescript-ui-calendar": "^6.1.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.10.3"
  },

ERROR ***********************************************************************************************************************

There is no appropriate source code format in 'C:/Users/shama/TravelGo/node_modules/nativescript-datetimepicker' entry-point.
    at DependencyResolver.getEntryPointFormatInfo (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\dependencies\dependency_resolver.js:164:19)        
    at DependencyResolver.getEntryPointWithDependencies (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\dependencies\dependency_resolver.js:70:39)   
    at DirectoryWalkerEntryPointFinder.walkDirectoryForPackages (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:87:48)
    at DirectoryWalkerEntryPointFinder.walkDirectoryForPackages (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:114:79)
    at C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:64:80
    at Object.trackDuration (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\utils.js:92:22)
    at DirectoryWalkerEntryPointFinder.walkBasePathForPackages (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:64:39)
    at DirectoryWalkerEntryPointFinder.findEntryPoints (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:42:30)
    at C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:27:41
    at new ClusterMaster (C:\Users\shama\TravelGo\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:44:30)
C:\Users\shama\TravelGo\node_modules\webpack-cli\bin\cli.js:453
                                throw err;
                                ^

Error: NGCC failed.
    at NgccProcessor.process (C:\Users\shama\TravelGo\node_modules\@ngtools\webpack\src\ngcc_processor.js:76:19)
    at C:\Users\shama\TravelGo\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:579:31
    at SyncHook.eval [as call] (eval at create (C:\Users\shama\TravelGo\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (C:\Users\shama\TravelGo\node_modules\tapable\lib\Hook.js:154:20)
    at webpack (C:\Users\shama\TravelGo\node_modules\webpack\lib\webpack.js:51:30)   
    at processOptions (C:\Users\shama\TravelGo\node_modules\webpack-cli\bin\cli.js:441:16)
    at C:\Users\shama\TravelGo\node_modules\webpack-cli\bin\cli.js:536:3
    at Object.parse (C:\Users\shama\TravelGo\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at C:\Users\shama\TravelGo\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (C:\Users\shama\TravelGo\node_modules\webpack-cli\bin\cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)        
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\shama\TravelGo\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)        
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Executing webpack failed with exit code 1.

**Comment by Robernator** [comment]
You need this:
"@nativescript/datetimepicker": "~2.1.0",
