### ISSUE TITLE
Version "1.2.3" iOS version "13.3" issue

### ISSUE THREAD

**Issue by sfrcnayds** [NativeScript/nativescript-datetimepicker#80]
I have an issue on plugin version "1.2.3" and iOS version "13.3".

Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want.
Try this:
(1) look at each constraint and try to figure out which you don't expect;
(2) find the code that added the unwanted constraint or constraints and fix it.
(
"<NSLayoutConstraint:0x283f9b5c0 UIView:0x122928450.width == - 16   (active)>"
)
Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x283f9b5c0 UIView:0x122928450.width == - 16   (active)>
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
-[TNSDictionaryAdapter set]: unrecognized selector sent to instance 0x281cb7e60
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x105152348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10519c428 -[TNSRuntime executeModule:referredBy:]
3   0x1040e6eb0
4   0x19cab8360 <redacted>
JavaScript stack trace:
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:2923:144
at ./main.ts(file:///app/bundle.js:2928:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
JavaScript error:
file: node_modules/@nativescript/core/application/application.ios.js:312:0: JS ERROR Error: -[TNSDictionaryAdapter set]: unrecognized selector sent to instance 0x281cb7e60
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x105152348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105199ed4 -[TNSRuntimeInspector reportFatalError:]
3   0x1040e8d64
4   0x19ccb6d50 <redacted>
5   0x19c9de24c <redacted>
6   0x19ca83304 <redacted>
7   0x19ca82c58 __cxa_get_exception_ptr
8   0x19ca82c18 <redacted>
9   0x19c9de0d0 <redacted>
10  0x105152820 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x10519c428 -[TNSRuntime executeModule:referredBy:]
12  0x1040e6eb0
13  0x19cab8360 <redacted>
JavaScript stack trace:
JavaScript error:
JS ERROR Error: NativeScript encountered a fatal error: Error: -[TNSDictionaryAdapter set]: unrecognized selector sent to instance 0x281cb7e60
at
UIApplicationMain(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:2923:144
at ./main.ts(file:///app/bundle.js:2928:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
NativeScript caught signal 6.
Native Stack:
1   0x10519b018 sig_handler(int)
2   0x19c9c4884 <redacted>
3   0x19c9c91d8 <redacted>
4   0x19c91d844 abort
5   0x19ca767d4 __cxa_bad_cast
6   0x19ca83324 <redacted>
7   0x19ca82c58 __cxa_get_exception_ptr
8   0x19ca82c18 <redacted>
9   0x19c9de0d0 <redacted>
10  0x105152820 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
11  0x10519c428 -[TNSRuntime executeModule:referredBy:]
12  0x1040e6eb0
13  0x19cab8360 <redacted>
JS Stack:

**Comment by mouadhkaabachi** [comment]
same error

**Comment by Przemase** [comment]
The same error on ios 12.4 on emulator and real device

This isue is releate with https://github.com/NativeScript/nativescript-datetimepicker/issues/78
Modify datetimepicker.ios.js with this to fix it
    

DateTimePicker._applyDialogSpinnersColors = function (nativePicker, nativeContainer, color, backgroundColor) {​​​​​​​​
if (backgroundColor) {​​​​​​​​
nativeContainer.backgroundColor = backgroundColor.ios;
 }​​​​​​​​
if (color) {​​​​​​​​
if (this.SUPPORT_TEXT_COLOR) {​​​​​​​​
nativePicker.setValueForKey(**color.ios**, 'textColor');
 }​​​​​​​​
nativePicker.setValueForKey(false, "highlightsToday");
 }​​​​​​​​
 }​​​​​​​​;


Tested on Emulator ISO 12.4 and real device with IOS 12.5
